// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StudentDatabase.Data;

#nullable disable

namespace StudentWeb.Migrations
{
    [DbContext(typeof(StudentContext))]
    [Migration("20230507124539_01")]
    partial class _01
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("StudentDatabase.Data.Models.Course", b =>
                {
                    b.Property<int>("CourseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CourseId"));

                    b.Property<string>("Description")
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(80)");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("CourseId");

                    b.ToTable("Courses");

                    b.HasData(
                        new
                        {
                            CourseId = 1,
                            Description = "Math studing",
                            EndDate = new DateTime(2023, 5, 7, 15, 45, 38, 588, DateTimeKind.Local).AddTicks(8304),
                            Name = "Math",
                            Price = 1000,
                            StartDate = new DateTime(2023, 5, 7, 15, 45, 38, 583, DateTimeKind.Local).AddTicks(4947)
                        },
                        new
                        {
                            CourseId = 2,
                            Description = "Programming studing",
                            EndDate = new DateTime(2023, 5, 7, 15, 45, 38, 588, DateTimeKind.Local).AddTicks(9409),
                            Name = "Programming",
                            Price = 2000,
                            StartDate = new DateTime(2023, 5, 7, 15, 45, 38, 588, DateTimeKind.Local).AddTicks(9388)
                        });
                });

            modelBuilder.Entity("StudentDatabase.Data.Models.Homework", b =>
                {
                    b.Property<int>("HomeworkId")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<DateTime>("SubmissionTime")
                        .HasColumnType("datetime2");

                    b.HasKey("HomeworkId");

                    b.HasIndex("CourseId");

                    b.ToTable("Homeworks");

                    b.HasData(
                        new
                        {
                            HomeworkId = 1,
                            Content = "Task",
                            ContentType = "Pdf",
                            CourseId = 1,
                            StudentId = 1,
                            SubmissionTime = new DateTime(2023, 5, 7, 15, 45, 38, 607, DateTimeKind.Local).AddTicks(7843)
                        },
                        new
                        {
                            HomeworkId = 2,
                            Content = "Task",
                            ContentType = "Aplication",
                            CourseId = 2,
                            StudentId = 1,
                            SubmissionTime = new DateTime(2023, 5, 7, 15, 45, 38, 607, DateTimeKind.Local).AddTicks(8812)
                        });
                });

            modelBuilder.Entity("StudentDatabase.Data.Models.Resource", b =>
                {
                    b.Property<int>("ResourceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ResourceId"));

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ResourceType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ResourceId");

                    b.HasIndex("CourseId");

                    b.ToTable("Resources");

                    b.HasData(
                        new
                        {
                            ResourceId = 1,
                            CourseId = 1,
                            Name = "Integral video",
                            ResourceType = "Video",
                            Url = "www.video.com"
                        },
                        new
                        {
                            ResourceId = 2,
                            CourseId = 2,
                            Name = "С# video",
                            ResourceType = "Video",
                            Url = "www.video.com"
                        });
                });

            modelBuilder.Entity("StudentDatabase.Data.Models.Student", b =>
                {
                    b.Property<int>("StudentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StudentId"));

                    b.Property<DateTime>("Birthday")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<DateTime>("RegisteredOn")
                        .HasColumnType("datetime2");

                    b.HasKey("StudentId");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            StudentId = 1,
                            Birthday = new DateTime(2023, 5, 7, 15, 45, 38, 615, DateTimeKind.Local).AddTicks(316),
                            Name = "Oleh",
                            PhoneNumber = "+123456789",
                            RegisteredOn = new DateTime(2023, 5, 7, 15, 45, 38, 614, DateTimeKind.Local).AddTicks(9663)
                        },
                        new
                        {
                            StudentId = 2,
                            Birthday = new DateTime(2023, 5, 7, 15, 45, 38, 615, DateTimeKind.Local).AddTicks(968),
                            Name = "Stepan",
                            PhoneNumber = "+123456789",
                            RegisteredOn = new DateTime(2023, 5, 7, 15, 45, 38, 615, DateTimeKind.Local).AddTicks(943)
                        });
                });

            modelBuilder.Entity("StudentDatabase.Data.Models.StudentCourse", b =>
                {
                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.HasKey("CourseId");

                    b.HasIndex("StudentId");

                    b.ToTable("StudentCources");
                });

            modelBuilder.Entity("StudentDatabase.Data.Models.Homework", b =>
                {
                    b.HasOne("StudentDatabase.Data.Models.Course", "Course")
                        .WithMany("Homeworks")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StudentDatabase.Data.Models.Student", "Student")
                        .WithMany("Homeworks")
                        .HasForeignKey("HomeworkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("StudentDatabase.Data.Models.Resource", b =>
                {
                    b.HasOne("StudentDatabase.Data.Models.Course", "Course")
                        .WithMany("Resources")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");
                });

            modelBuilder.Entity("StudentDatabase.Data.Models.StudentCourse", b =>
                {
                    b.HasOne("StudentDatabase.Data.Models.Course", "Course")
                        .WithMany("StudentCources")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StudentDatabase.Data.Models.Student", "Student")
                        .WithMany("StudentCources")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("StudentDatabase.Data.Models.Course", b =>
                {
                    b.Navigation("Homeworks");

                    b.Navigation("Resources");

                    b.Navigation("StudentCources");
                });

            modelBuilder.Entity("StudentDatabase.Data.Models.Student", b =>
                {
                    b.Navigation("Homeworks");

                    b.Navigation("StudentCources");
                });
#pragma warning restore 612, 618
        }
    }
}
